/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Sermon = IDL.Record({
  'id' : IDL.Nat8,
  'preacher' : IDL.Text,
  'title' : IDL.Text,
  'audioUrl' : IDL.Opt(IDL.Text),
  'sermonDate' : Time,
  'sermonText' : IDL.Text,
  'scriptureReference' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'submittedAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSermon' : IDL.Func([Sermon], [IDL.Nat8], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getSermonById' : IDL.Func([IDL.Nat8], [IDL.Opt(Sermon)], ['query']),
  'getServiceInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'address' : IDL.Text,
          'mapUrl' : IDL.Text,
          'serviceTimes' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSermon' : IDL.Func([Sermon], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Sermon = IDL.Record({
    'id' : IDL.Nat8,
    'preacher' : IDL.Text,
    'title' : IDL.Text,
    'audioUrl' : IDL.Opt(IDL.Text),
    'sermonDate' : Time,
    'sermonText' : IDL.Text,
    'scriptureReference' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'submittedAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSermon' : IDL.Func([Sermon], [IDL.Nat8], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllSermons' : IDL.Func([], [IDL.Vec(Sermon)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getSermonById' : IDL.Func([IDL.Nat8], [IDL.Opt(Sermon)], ['query']),
    'getServiceInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'address' : IDL.Text,
            'mapUrl' : IDL.Text,
            'serviceTimes' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSermon' : IDL.Func([Sermon], [], []),
  });
};

export const init = ({ IDL }) => { return []; };